---
version: "2"
services:
  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana_container
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
volumes:
  grafana-volume:
    name: grafana-volume	