---
version: "2"
services:
  node-red:
    image: nodered/node-red:3.1.5
    container_name: node-red
    restart: unless-stopped
    ports:
      - 1880:1880
      - 5858:5858/udp
    volumes:
      - nodered-volume:/data
volumes:
  nodered-volume:
    name: nodered-volume
    